# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c385940efbc6d542792a726725df7ded527fc18a5a94179b47a9cf901461c845c2d2a93b8c2c573bb9c24beb8a06742cdf187d0735912193ad44beaa7a03b4

test:
  secret_key_base: 44c8dd15f9a6f99ff5e2f064a5d51a17ae42ef393c2e2d4a502946de9bb3a75edb90ed022caca80833d0372da96fd6c2fd354ce03b745dc785779a1bffcfaf1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
